spring:
  datasource:
    username: mc
    password: password
    driver-class-name: org.postgresql.Driver
    name: metrics_consumer_db
    url: jdbc:postgresql://localhost:5432/metrics_consumer_db
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
    generate-ddl: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: metrics-events
      properties:
        spring:
          json:
            trusted:
              packages: "com.pvxdv.*"

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html