spring:
  application:
    name: consumer_service
  datasource:
    username: sc
    password: password
    driver-class-name: org.postgresql.Driver
    name: consumer_service_db
    url: jdbc:postgresql://localhost:5432/consumer_service_db
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
    generate-ddl: true
server:
  port: 8081
